openapi: 3.0.0
# setup info
info:
  title: Tshirt Store API - AryanNipane
  description: LCO - a course to create api for ecomm store (maintain docs if have a time)
  version: 1.1.0
  contact:
    name: AryanNipane
    email: aryan@gmail.com
    url: "https://aryannipane.netlify.app"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

# authentication and authorization
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

security:
  - cookieAuth: []

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: return a greet message
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: bad request
        500:
          description: internal server error
